const burgers = [
  {
    id: 1,
    name: "classic burger",
    ingredients: "Beef patty, lettuce, tomato, onion, pickles, and cheddar cheese",
    price: 12.99,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 2,
    name: "cheeseburger",
    ingredients: "Beef patty, lettuce, tomato, onion, pickles, cheddar cheese, and mayo",
    price: 13.49,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 3,
    name: "bacon burger",
    ingredients: "Beef patty, lettuce, tomato, onion, bacon, cheddar cheese, and BBQ sauce",
    price: 11.79,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 4,
    name: "mushroom swiss burger",
    ingredients: "Beef patty, sautéed mushrooms, swiss cheese, lettuce, tomato, and mayo",
    price: 12.25,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 5,
    name: "spicy chicken burger",
    ingredients: "Grilled chicken breast, lettuce, tomato, onion, jalapeños, pepper jack cheese, and spicy mayo",
    price: 14.99,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 6,
    name: "veggie burger",
    ingredients: "Grilled vegetable patty, lettuce, tomato, onion, avocado, and provolone cheese",
    price: 12.75,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 7,
    name: "double cheeseburger",
    ingredients: "Two beef patties, lettuce, tomato, onion, pickles, cheddar cheese, and mayo",
    price: 13.99,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 8,
    name: "western burger",
    ingredients: "Beef patty, lettuce, tomato, onion rings, bacon, cheddar cheese, and BBQ sauce",
    price: 12.50,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 9,
    name: "avocado burger",
    ingredients: "Beef patty, lettuce, tomato, avocado, bacon, pepper jack cheese, and spicy mayo",
    price: 12.95,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 10,
    name: "teriyaki burger",
    ingredients: "Beef patty, lettuce, tomato, grilled pineapple, teriyaki sauce, swiss cheese, and mayo",
    price: 12.35,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 11,
    name: "guacamole burger",
    ingredients: "Beef patty, lettuce, tomato, guacamole, bacon, pepper jack cheese, and chipotle mayo",
    price: 12.70,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
  {
    id: 12,
    name: "black bean burger",
    ingredients: "Black bean patty, lettuce, tomato, onion, roasted red pepper, avocado, and pepper jack cheese",
    price: 12.80,
    photoName: "https://www.unileverfoodsolutions.com.co/dam/global-ufs/mcos/NOLA/calcmenu/recipes/col-recipies/fruco-tomate-cocineros/HAMBURGUESA%201200x709.png",
    soldOut: false,
  },
];

module.exports = burgers;
